name: full end to end devsecops workflow
on: push


jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - run: npm install
    - name: SonarCloud scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=qiushengchu
          -Dsonar.projectKey=endtoendnodeJS
          -Dsonar.verbose=true
  snyk:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@master
      - name: Run synk to check for vulnerabilities
        uses: snyk/actions/node@master
        env: 
          SYNK_TOKEN: ${{ secrets.SNYK_TOKEN }}
